imports:
    - { resource: tables.yml }

services:
    paul999.ajaxshoutbox.listener:
        class: paul999\ajaxshoutbox\event\shoutbox_listener
        arguments:
            - @user
            - @template
        tags:
            - { name: event.listener }

